### ISSUE TITLE
LoggingAdmin NullPointerException

### ISSUE THREAD

**Issue by littlecong** [wso2/carbon-commons#256]
in logging components
class org.wso2.carbon.logging.service.LoggingAdmin
method private Appender getAppenderInLoggerWithName(Logger logger, String appenderName) 
  appender.getName() will return null when the appender is org.apache.solr.logging.log4j.EventAppender.

Caused by: java.lang.NullPointerException
	at org.wso2.carbon.logging.service.LoggingAdmin.getAppenderInLoggerWithName(LoggingAdmin.java:550)
	at org.wso2.carbon.logging.service.LoggingAdmin.getAppenderData(LoggingAdmin.java:153)

It will recur in wso2as-5.3.0

**Comment by jsdjayanga** [comment]
Thanks for reporting. This issue was fixed with the following commit
https://github.com/wso2/carbon-commons/commit/ade18348cc229734e53e15483401457bdd69baa7
